### ISSUE TITLE
how to set spring context-path from docker-compose variable?

### ISSUE THREAD

**Issue by lynings** [kekingcn/kkFileView#127]
I need to add context-path to avoid conflict with static files of other services.

I hope: 

nginx(default.conf)
```
    location ^~ /preview/onlinePreview {
        proxy_pass http://preview-server$request_uri;
        .......
    }

    location ^~ /preview/js {
        proxy_pass http://preview-server$request_uri;
        .......
    }
..........
```

docker-compose.yml
```
version: '3.5'
services:
    preview-server:
        container_name: preview-server
        image: keking/kkfileview:latest
        restart: always
        ports:
            - 8012:8012
        environment:
            - KK_CONTEXT_PATH=/preview
.....
```

but environment invalid for docker-compose.yml
